### ISSUE TITLE
Question: How would the DSL translate into JSON

### ISSUE THREAD

**Issue by donhector** [wiremock/wiremock-webhooks-extension#1]
Hi, this extension looks very neat and would definitely cover many scenarios not covered by Wiremock out of the box (i.e. mocking asynchronous  REST APIs)

I was wondering if creating stubs that use this extension is also possible via JSON over HTTP, and if so, what would be the format of the JSON one would need to POST to Wiremock to set up stubs that leverage this webhooks extension.

I'm familiar with transformers but this extension seems to use a different approach (`PostServeAction`) so I'm not quite sure  how the JSON over HTTP would look like for this extension.

For example, given your example DSL:

```
rule.stubFor(post(urlPathEqualTo("/something-async"))
        .willReturn(aResponse().withStatus(200))
        .withPostServeAction("webhook", webhook()
            .withMethod(POST)
            .withUrl("http://localhost:" + targetServer.port() + "/callback")
            .withHeader("Content-Type", "application/json")
            .withBody("{ \"result\": \"SUCCESS\" }"))
    );
```

What JSON should one curl to Wiremock to setup stubs like the one above? Having some examples would be awesome.

**Comment by tomakehurst** [comment]
Tagging as enhancement as I should document this

**Comment by tomakehurst** [comment]
Yes, it's possible to do this with JSON over HTTP.

Here's an example:

```json
{
  "request" : {
    "urlPath" : "/something",
    "method" : "POST"
  },
  "response" : {
    "status" : 200
  },
  "postServeActions" : {
    "webhook" : {
      "headers" : {
        "Content-Type" : "application/json"
      },
      "method" : "POST",
      "body" : "{ \"result\": \"SUCCESS\" }",
      "url" : "http://localhost:56299/callback"
    }
  }
}
```

**Comment by tomakehurst** [comment]
Incidentally, here's way to get the JSON representation of something produced by the DSL:

```java
System.out.println(Json.write(post(urlPathEqualTo("/something"))
                .willReturn(aResponse().withStatus(200))
                .withPostServeAction("webhook", webhook()
                        .withMethod(POST)
                        .withUrl("http://localhost:" + targetServer.port() + "/callback")
                        .withHeader("Content-Type", "application/json")
                        .withBody("{ \"result\": \"SUCCESS\" }")).build()));
```

**Comment by donhector** [comment]
Excellent! And thanks for the very prompt response.
